config/routes.rb
Rails.application.routes.draw do

  root 'searches#home'
  match '/result',    to: 'searches#result',    via: 'post'
  match '/saverecord', to: 'searches#saverecord', via: 'post'

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
require 'open-uri'
require 'uri'
require 'rexml/document'

class SearchesController < ApplicationController

  def home
    @searched_words = Search.all
  end

  def result
    @search_word = params[:search_word]
    @suggestions = create_suggestions(params[:search_word])
  end

  def saverecord
    searched_word = params[:searched_word]
    @words = params[:suggested_words].split("/")
    Search.create(search_word: searched_word, rel1: @words[0], rel2: @words[1], rel3: @words[2], rel4: @words[3], rel5: @words[4])
  end

  private

    def create_suggestions(query)
      encoded_query = URI.encode(query)
      url = "http://www.google.com/complete/search?h1=ja&output=toolbar&q=#{encoded_query}"
      REXML::Document.new(open(url).read.encode('UTF-8'))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dbtest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/home.html.erb
<h1>入力された単語の関連語を10個表示します</h1>

<%= form_tag('/result') do %>
<div>
  <%= text_field_tag :search_word, "", placeholder: '単語を入力してください' %>
  <%= submit_tag '送信' %>
</div>
<% end %>

<% unless @searched_words.empty? %>
<p>これまでの検索結果</p>
<ul>
<% @searched_words.each do |word| %>
  <li>
    検索語：<%= word.search_word %>　関連語：<%= word.rel1 %>, <%= word.rel2 %>, <%= word.rel3 %>, <%= word.rel4 %>, <%= word.rel5 %>
  </li>
<% end %>
</ul>
<% end %>

app/views/searches/result.html.erb
<h1>Suggestions</h1>

<% suggested_words = [] %>
<% @suggestions.elements.each('toplevel/CompleteSuggestion/suggestion') do |element| %>
  <p><%= element.attributes["data"] %></p>
  <% next if suggested_words.length == 5 %>
  <% suggested_words << element.attributes["data"] %>
<% end %>

<%= button_to '関連語上位５件をDBに保存', saverecord_path, params: { searched_word: @search_word, suggested_words: suggested_words } %>

app/views/searches/saverecord.html.erb
<ul>
<% @words.each do |word| %>
  <li><%= word %></li>
<% end %>
</ul>
<p>以上がデータベースに保存されました。</p>
<%= link_to 'トップへ戻る', root_path %>